name: PowerShell Azure

on:

  workflow_dispatch:
    inputs:
      UserCount:
        description: 'Number of users should match Terraform build (0-99)'
        required: true
        default: '0'
        type: string
      UserStart:
        description: 'Starting index for user numbering'
        required: false
        default: '0'
        type: string
jobs:
  PowerShell:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub Actions variables
        run: |
          if [[ ${{ github.event_name == 'workflow_dispatch' }} == true ]]; then
            user_start=${{ inputs.UserStart }}
            user_count=${{ inputs.UserCount }}
          else
            user_start=${{ vars.ENV_USER_START }}
            user_count=${{ vars.ENV_USER_COUNT }}
          fi

          echo "user_start=$user_start" >> $GITHUB_ENV
          echo "user_count=$user_count" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Run Azure PowerShell script
        shell: pwsh
        run: |
          Install-Module -Name Az.Resources -AllowClobber -Force -Scope CurrentUser
          Install-Module -Name Microsoft.Entra.DirectoryManagement -AllowClobber -Force -Scope CurrentUser
          Install-Module -Name Microsoft.Entra.Authentication -AllowClobber -Force -Scope CurrentUser

          Connect-Entra -Scopes 'Organization.Read.All, LicenseAssignment.Read.All'
          Get-EntraSubscribedSku | Where-Object { $_.SkuPartNumber -eq "WACONEDRIVESTANDARD" } | Select-Object *